imports:
    - { resource: tables.yml }

services:
    mot.hangman.controller:
        class: mot\hangman\controller\main
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.hangman.tables.mot_hangman_score%'
            - '%mot.hangman.tables.mot_hangman_words%'

    mot.hangman.listener:
        class: mot\hangman\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
