services:
    mot.hangman.controller:
        class: mot\hangman\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    mot.hangman.listener:
        class: mot\hangman\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
