parameters:
    mot.hangman.tables.mot_hangman_score: '%core.table_prefix%mot_hangman_score'
    mot.hangman.tables.mot_hangman_words: '%core.table_prefix%mot_hangman_words'
    mot.hangman.tables.old_hangman_words: '%core.table_prefix%hangman_words'
